import localFont from "next/font/local";
import "./globals.css";
import Head from 'next/head';
import Navbar from '../components/Navbar';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Outlet Expense",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head><link rel="icon" href="/favicon.ico"/></Head>
      <header className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
      <link rel="icon" href="/favicon.ico" />
      <Navbar />
      </header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
      </footer>
    </html>
  );
}
