import localFont from "next/font/local";
import "./globals.css";
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Outlet Expense",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head><link rel="icon" href="/favicon.ico"/></Head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
      <header className="flex gap-6 flex-wrap items-center justify-center">
      <Navbar />
      </header>
        {children}
        <footer className="flex gap-6 flex-wrap items-center justify-center">
          <Footer/>
        </footer>
      </body>

    </html>
  );
}
