/* "use client";
import React, { useState } from 'react';
import Image from "next/image";
import { ChevronDownIcon, ChevronUpIcon } from '@heroicons/react/24/solid';

const faqsData = [
  {
    question: "What is Outlet Expense?",
    answer: "Outlet Expense is an advanced inventory management system that helps businesses track and manage products, expenses, and profits efficiently.",
  },
  {
    question: "How does the profit calculation work?",
    answer: "Our system calculates profit for both product types with and without variants, even if they appear in the same transaction.",
  },
  {
    question: "Can I manage multiple payments and dues?",
    answer: "Yes, Outlet Expense supports multi-payment systems and due collection management for customers.",
  },
  {
    question: "Is support available for my organization?",
    answer: "Yes, we provide full technical support to ensure your organization operates smoothly with our system.",
  },
  {
    question: "Is there a trial period for Outlet Expense?",
    answer: "Yes, we offer a free trial period for new users to explore the features and benefits of Outlet Expense before making a commitment.",
  },
  {
    question: "How can I integrate Outlet Expense with my current systems?",
    answer: "Outlet Expense provides API access and documentation to ensure smooth integration with your existing systems, such as accounting or e-commerce platforms.",
  },
  {
    question: "Does Outlet Expense handle inventory across multiple locations?",
    answer: "Yes, Outlet Expense allows you to track inventory levels across multiple store locations and warehouses in real-time.",
  },
  {
    question: "How often is my data backed up?",
    answer: "We ensure automatic daily backups for all your data, safeguarding against any potential loss.",
  },
  {
    question: "Can I customize the reports generated by Outlet Expense?",
    answer: "Yes, Outlet Expense provides customizable reporting tools that allow you to generate specific reports based on your business needs.",
  },
  {
    question: "What payment methods are accepted?",
    answer: "We accept all major credit cards, PayPal, and bank transfers for our subscription plans.",
  }
];

const FAQItem = ({ faq, isOpen, toggle }) => (
  <div className="border-b border-gray-200 py-6">
    <div
      className="flex justify-between items-center cursor-pointer"
      onClick={toggle}
    >
      <h3 className="text-xl font-semibold text-gray-900">{faq.question}</h3>
      {isOpen ? (
        <ChevronUpIcon className="w-6 h-6 text-indigo-500" />
      ) : (
        <ChevronDownIcon className="w-6 h-6 text-indigo-500" />
      )}
    </div>
    <div
      className={`mt-4 text-base text-gray-600 transition-all duration-300 ease-in-out ${
        isOpen ? 'max-h-screen opacity-100' : 'max-h-0 opacity-0 overflow-hidden'
      }`}
    >
      <p>{faq.answer}</p>
    </div>
  </div>
);

const Faqs = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleFaq = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-indigo-100 py-16 pt-28">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8"> 
        <div className='flex items-center justify-between'>
            <h1 className="text-5xl font-bold text-center text-gray-900 mb-3 bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
            Frequently Asked Questions
            </h1>
            <Image
                src="/faq-image.svg" // Replace with your image path
                alt="Logo"
                width={400} // Adjust the width as per your needs
                height={350} // Adjust the height as per your needs
              />
        </div>
        
        <div className="space-y-6 md:space-y-10 mt-20">
          {faqsData.map((faq, index) => (
            <FAQItem
              key={index}
              faq={faq}
              isOpen={openIndex === index}
              toggle={() => toggleFaq(index)}
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default Faqs; */

"use client";
import React, { useState } from "react";
import Image from "next/image";
import { ChevronDownIcon } from "@heroicons/react/24/solid";

const faqGroups = [
  {
    title: "Platform & onboarding",
    faqs: [
      {
        question: "What is Outlet Expense?",
        answer:
          "Outlet Expense is a composable inventory and operations OS that unifies POS, finance, HRM, and exporter workflows inside a single futuristic console.",
      },
      {
        question: "How fast can we go live?",
        answer:
          "Most teams launch their first market or store network in 3–4 weeks with white-glove onboarding, process mapping, and data migration support.",
      },
      {
        question: "Do you offer a trial or pilot period?",
        answer:
          "Yes. We offer guided pilots so your team can evaluate modules, connect data, and validate ROI before committing to a full rollout.",
      },
      {
        question: "Can Outlet Expense scale with enterprise requirements?",
        answer:
          "Absolutely. We support multi-country deployments, audit-ready permissions, and dedicated success teams for enterprise accounts.",
      },
    ],
  },
  {
    title: "Inventory & operations",
    faqs: [
      {
        question: "Does Outlet Expense handle multi-location inventory?",
        answer:
          "Yes. Monitor every warehouse and storefront in real time, automate transfers, and set per-location safety stock with predictive guidance.",
      },
      {
        question: "How does profit and reconciliation work?",
        answer:
          "Our ledger unifies POS, wholesale, and subscription revenue. You can reconcile mixed payment methods and variance down to each SKU.",
      },
      {
        question: "Can we integrate with existing systems?",
        answer:
          "We provide REST APIs, webhooks, and pre-built connectors for ERPs, accounting suites, eCommerce platforms, and logistics providers.",
      },
      {
        question: "What about HRM and finance workflows?",
        answer:
          "HRM, finance, and exporter modules ship with the same interface. Approvals, payroll, budgeting, and compliance documents are orchestrated in one pane.",
      },
    ],
  },
  {
    title: "Security & support",
    faqs: [
      {
        question: "How is our data protected?",
        answer:
          "We enforce SOC 2 and ISO 27001 controls, end-to-end encryption, daily backups, and granular access layers with biometric approvals.",
      },
      {
        question: "What kind of support is included?",
        answer:
          "24/7 incident response, dedicated customer success, and monthly optimization sessions are included for all plans.",
      },
      {
        question: "What payment methods do you accept?",
        answer:
          "Major credit cards, bank transfers, and custom invoicing for enterprise agreements are all supported.",
      },
      {
        question: "Can we customize reports?",
        answer:
          "Yes. Build role-based dashboards, export via CSV/API, or push data to your warehouse with our analytics toolkit.",
      },
    ],
  },
];

const badges = [
  "SOC 2 & ISO 27001",
  "99.99% uptime SLA",
  "Dedicated success partner",
  "Global data residency",
];

const contactCards = [
  {
    label: "Talk to sales",
    detail: "Schedule a tailored walkthrough for your team",
    cta: "Book a session",
    href: "https://pos.outletexpense.com/signup",
  },
  {
    label: "Get technical docs",
    detail: "Review APIs, webhooks, and integration guides",
    cta: "Explore docs",
    href: "/features",
  },
  {
    label: "24/7 support desk",
    detail: "Email squadinnovators@gmail.com or call +880 1677-182084",
    cta: "Contact support",
    href: "mailto:squadinnovators@gmail.com",
  },
];

const FAQItem = ({ faq, idx, current, onToggle }) => {
  const isOpen = current === idx;
  return (
    <div
      className={`rounded-3xl border border-slate-200/70 bg-white/80 p-6 shadow-lg backdrop-blur dark:border-white/10 dark:bg-white/5 ${
        isOpen ? "ring-1 ring-sky-400/50 dark:ring-sky-400/60" : ""
      }`}
    >
      <button
        className="flex w-full items-center justify-between text-left"
        onClick={() => onToggle(isOpen ? null : idx)}
        aria-expanded={isOpen}
      >
        <span className="text-lg font-semibold text-slate-900 dark:text-white">{faq.question}</span>
        <span
          className={`rounded-full border border-slate-200/70 p-2 text-slate-600 transition dark:border-white/20 dark:text-white/70 ${
            isOpen ? "bg-slate-100 dark:bg-white/10" : ""
          }`}
        >
          <ChevronDownIcon
            className={`h-4 w-4 transition-transform duration-200 ${isOpen ? "rotate-180" : ""}`}
          />
        </span>
      </button>
      <div
        className={`grid transition-[grid-template-rows] duration-300 ease-in-out ${
          isOpen ? "mt-4 grid-rows-[1fr]" : "grid-rows-[0fr]"
        }`}
      >
        <div className="overflow-hidden text-sm leading-relaxed text-slate-600 dark:text-white/70">
          <p>{faq.answer}</p>
        </div>
      </div>
    </div>
  );
};

const Faqs = () => {
  const [openIndex, setOpenIndex] = useState(null);
  const flattenFaqs = faqGroups.flatMap((group) => group.faqs);

  return (
    <div className="min-h-screen bg-gradient-to-b from-white via-slate-50 to-white text-slate-900 dark:from-[#020617] dark:via-[#050b1d] dark:to-[#020617] dark:text-white">
      {/* Hero */}
      <section className="relative overflow-hidden pb-20 pt-32">
        <div className="absolute inset-0 opacity-40 blur-3xl">
          <div className="absolute inset-y-0 left-1/4 w-[700px] rounded-full bg-[radial-gradient(circle,_rgba(59,130,246,0.3),_transparent_70%)] dark:bg-[radial-gradient(circle,_rgba(56,189,248,0.35),_transparent_70%)]" />
          <div className="absolute right-0 top-10 w-[400px] rounded-full bg-[radial-gradient(circle,_rgba(56,189,248,0.25),_transparent_70%)]" />
        </div>
        <div className="relative mx-auto flex max-w-6xl flex-col gap-10 px-6 md:flex-row md:items-center">
          <div className="space-y-6 md:w-1/2">
            <p className="text-xs uppercase tracking-[0.5em] text-slate-500 dark:text-slate-300">
              FAQ hub
            </p>
            <h1 className="text-4xl font-semibold leading-tight md:text-5xl">
              Everything you need to run{" "}
              <span className="bg-gradient-to-r from-sky-400 via-blue-500 to-emerald-400 bg-clip-text text-transparent">
                inventory operations without noise
              </span>
            </h1>
            <p className="text-lg text-slate-600 dark:text-white/70">
              Answers to the most common questions from retail founders, finance leads, and
              operations teams evaluating Outlet Expense.
            </p>
            <div className="flex flex-wrap gap-3">
              {badges.map((badge) => (
                <span
                  key={badge}
                  className="rounded-full border border-slate-200/80 px-4 py-1 text-xs uppercase tracking-[0.3em] text-slate-500 dark:border-white/20 dark:text-white/60"
                >
                  {badge}
                </span>
              ))}
            </div>
          </div>
          <div className="md:w-1/2">
            <div className="rounded-[32px] border border-slate-200/70 bg-white/80 p-6 shadow-2xl dark:border-white/10 dark:bg-white/5">
              <Image
                src="/faq-image.svg"
                alt="FAQ hero"
                width={520}
                height={420}
                className="w-full object-contain"
              />
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Sections */}
      <section className="pb-16">
        <div className="mx-auto max-w-6xl px-6">
          <div className="space-y-12">
            {faqGroups.map((group, groupIdx) => (
              <div key={group.title} className="space-y-6">
                <div className="flex flex-col gap-3">
                  <p className="text-xs uppercase tracking-[0.4em] text-slate-500 dark:text-slate-300">
                    {group.title}
                  </p>
                  <div className="h-px w-16 bg-gradient-to-r from-sky-500 to-emerald-400" />
                </div>
                <div className="grid gap-5 md:grid-cols-2">
                  {group.faqs.map((faq, idx) => {
                    const absoluteIndex = faqGroups
                      .slice(0, groupIdx)
                      .reduce((count, g) => count + g.faqs.length, 0) + idx;
                    return (
                      <FAQItem
                        key={faq.question}
                        faq={faq}
                        idx={absoluteIndex}
                        current={openIndex}
                        onToggle={setOpenIndex}
                      />
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Still need help */}
      <section className="pb-28">
        <div className="mx-auto flex max-w-6xl flex-col gap-6 px-6 md:flex-row">
          <div className="md:w-1/2">
            <div className="rounded-[36px] bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-8 text-white shadow-[0_35px_120px_rgba(15,23,42,0.8)]">
              <p className="text-xs uppercase tracking-[0.4em] text-white/70">Need more?</p>
              <h3 className="mt-4 text-3xl font-semibold">
                Partner with a success engineer to map your rollout in hours.
              </h3>
              <p className="mt-4 text-white/70">
                Share your current stack, regions, and timeline—we'll co-design a plan with staged
                milestones, migration steps, and automation ideas.
              </p>
              <ul className="mt-6 space-y-3 text-sm text-white/80">
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-emerald-300" />
                  Priority onboarding windows
                </li>
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-emerald-300" />
                  Dedicated Slack channel + war room
                </li>
                <li className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-emerald-300" />
                  Migration kits for inventory, finance, HRM
                </li>
              </ul>
              <a
                href="https://pos.outletexpense.com/signup"
                className="mt-8 inline-flex items-center justify-center rounded-full bg-white px-6 py-3 text-slate-900 font-semibold transition hover:bg-slate-100"
              >
                Book a planning call
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="ml-2 h-4 w-4"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" d="M17.25 6.75L5.25 18.75M17.25 6.75H6.75M17.25 6.75V17.25" />
                </svg>
              </a>
            </div>
          </div>

          <div className="md:w-1/2 space-y-4">
            {contactCards.map((card) => (
              <div
                key={card.label}
                className="rounded-3xl border border-slate-200/70 bg-white/80 p-6 shadow-lg backdrop-blur dark:border-white/10 dark:bg-white/5"
              >
                <p className="text-xs uppercase tracking-[0.35em] text-slate-500 dark:text-white/60">
                  {card.label}
                </p>
                <p className="mt-3 text-lg text-slate-900 dark:text-white">{card.detail}</p>
                <a
                  href={card.href}
                  className="mt-6 inline-flex items-center text-sm font-semibold text-sky-600 dark:text-sky-300"
                >
                  {card.cta}
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="ml-2 h-4 w-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12l-7.5 7.5M21 12H3" />
                  </svg>
                </a>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
};

export default Faqs;